# Generated by Django 3.2.3 on 2021-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiwanStockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=100)),
                ('stock_id', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TaiwanStockInfo',
            },
        ),
    ]
