# Generated by Django 3.2.3 on 2021-05-20 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='hashed_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserSecretKeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('count', models.IntegerField()),
                ('is_charged', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
