# Generated by Django 3.2.3 on 2021-05-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersecretkeys_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersecretkeys',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
