# Generated by Django 3.2.3 on 2021-05-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210521_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecretkeys',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersecretkeys',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersecretkeys',
            name='is_charged',
            field=models.BooleanField(default=False),
        ),
    ]
