# Generated by Django 3.2.3 on 2021-05-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210525_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersecretkeys',
            old_name='user_id',
            new_name='user',
        ),
    ]
