# Generated by Django 3.2.3 on 2021-05-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_id_usersecretkeys_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersecretkeys',
            old_name='user',
            new_name='user_id',
        ),
    ]
