# Generated by Django 3.2.3 on 2021-05-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_usersecretkeys_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersecretkeys',
            old_name='user_id',
            new_name='user',
        ),
    ]
